sudo: false
language: ruby
cache: bundler
rvm:
- 2.1
script: bundle exec jekyll build --destination _site/theme && bundle exec htmlproof ./_site

branches:
  only:
    - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false
