title: ZJSU Theme
baseurl: /theme

disqus: zjsutheme

defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page

exclude: [LICENSE, Gemfile, Gemfile.lock, README.md, vendor]

sass:
    style: compressed
